// define translate
export const messages = {
    enUs: {
      message: {
        login: 'Login',
        plz_input_usr: 'Please input username',
        plz_input_pwd: 'Please input password',
        task: 'Task',
        current_task: 'Current Task',
        archive_task: 'Archive Task',
        project: 'Project',
        requesting: 'Requesting...',
        loging_failed:'Login Failed!',
        logout:'logout',
        logout_failed:'Logout Failed! But Token will be clean.',
        userManage: 'User Manage',
        taskManage: 'Task Manage',
        hello: 'Hello',
        message_failed: "Get info Failed!",
        username: "User Name",
        email: "Email",
        id: "ID",
        updated_at: "Last Updated",
        permission_level: "Permission Level",
        langSwitch: "Language switch successful.",
        compute_cluster: "Compute Cluster",
        update_user: "Update User",
      }
    },
    zhCn: {
      message: {
        login: '登录',
        plz_input_usr: '请输入用户名',
        plz_input_pwd: '请输入密码',
        task: '任务',
        current_task: '当前任务',
        archive_task: '存档任务',
        project: '项目',
        requesting: '请求中...',
        loging_failed:'登录失败！',
        logout:'登出',
        logout_failed:'登出失败！但是 Token 将被清除。',
        userManage: '用户管理',
        taskManage: '任务管理',
        hello: '你好',
        message_failed: "获取信息失败！",
        username: "用户名",
        email:"邮箱",
        id: "ID",
        updated_at: "上次更改时间",
        permission_level: "权限等级",
        langSwitch: "语言切换成功。",
        compute_cluster: "计算集群",
        update_user: "修改用户",
      }
    }
  };